#ifndef TYPES__H
#define TYPES__H

typedef enum {
	ERROR_CANTIDAD_ARGUMENTOS_INGRESADOS,
	ERROR_FLAG_SALIDA,
	ERROR_FLAG_ENTRADA,
	ERROR_FLAG_METODO,
	ERROR_NO_EXISTE_ARCHIVO_ENTRADA,
	ERROR_TIPO_TRANFORMADA,
	OK
} status_t;

#endif
